--user: amm password: admin--

CREATE DATABASE Nerdbook;

CREATE TABLE utenti (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(256),
	cognome VARCHAR(256),
	username VARCHAR(256),
	password VARCHAR(256),
	urlFoto VARCHAR(256),
	frase VARCHAR(512),
	dataDiNascita DATE,
	admin BOOLEAN
);

CREATE TABLE gruppi (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(256),
	urlFoto VARCHAR(256),
);

CREATE TABLE postType (
	id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(32)
);

CREATE TABLE posts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	autore INTEGER,
	bacheca_id INTEGER,
	gruppo_id INTEGER,
	testo VARCHAR(512),
	tipoAllegato INTEGER,
	allegato VARCHAR(512),
	FOREIGN KEY (autore) REFERENCES utenti (id),
	FOREIGN KEY (bacheca_id) REFERENCES utenti (id),
	FOREIGN KEY (gruppo_id) REFERENCES gruppi (id),
	FOREIGN KEY (tipoAllegato) REFERENCES postType (id)
);

CREATE TABLE amici (
	idU1 INTEGER,
	idU2 INTEGER,
	FOREIGN KEY (idU1) REFERENCES utenti(id),
	FOREIGN KEY (idU2) REFERENCES utenti(id),
	PRIMARY KEY (idU1, idU2)
);

CREATE TABLE utentiGruppi (
	id_utente INTEGER,
	id_gruppo INTEGER,
	FOREIGN KEY (id_utente) REFERENCES utenti(id),
	FOREIGN KEY (id_gruppo) REFERENCES gruppi(id),
	PRIMARY KEY (id_utente, id_gruppo)
);

INSERT INTO utenti (id,nome,cognome,username,password,urlFoto,frase,dataDiNascita,admin) VALUES (default,'Mario','Rossi','m.rossi1980','Hello123','img/propic.png','Ciao a tutti!','1/1/1980',false);
INSERT INTO utenti (id,nome,cognome,username,password,urlFoto,dataDiNascita,admin) VALUES (default,'Pinco','Pallino','p.pallino1992','Punto111','img/pincopallino.png','1/1/1992',false);

INSERT INTO amici (idU1,idU2) VALUES (2,4);
INSERT INTO amici (idU1,idU2) VALUES (4,2);

INSERT INTO gruppi (id,nome,urlFoto) VALUES (default,'Mongolfieristi','img/mongolfierabig.png');
INSERT INTO gruppi (id,nome,urlFoto) VALUES (default,'Ritardatari','img/clockbig.png');

INSERT INTO utentiGruppi (id_utente,id_gruppo) VALUES (2,1);
INSERT INTO utentiGruppi (id_utente,id_gruppo) VALUES (2,2);
INSERT INTO utentiGruppi (id_utente,id_gruppo) VALUES (4,1);

INSERT INTO postType (id, name) VALUES (default, 'NONE');
INSERT INTO postType (id, name) VALUES (default, 'LINK');
INSERT INTO postType (id, name) VALUES (default, 'IMAGE');

INSERT INTO posts (id,autore,bacheca_id,testo,tipoAllegato) VALUES (default,2,2,false,'Ciao a tutti!',1);
INSERT INTO posts (id,autore,bacheca_id,testo,tipoAllegato,allegato) VALUES (default,2,2,'Wow, guardate quanto è bella questa foto!',3,'img/Lorem-ipsum.jpg');
INSERT INTO posts (id,autore,bacheca_id,testo,tipoAllegato,allegato) VALUES (default,4,2,'Apri Mario!',2,'http://www.google.it');
INSERT INTO posts (id,autore,gruppo_id,,testo,tipoAllegato) VALUES (default,2,1,'Ciao mongolfieristi.',1);